cbseevents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('by-category/<tema_event>', EventListView.as_view(), name='event_tema_event'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

registration/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import RegisterEvent, RegistrationDetail, RegisterStudentList
from .views import EnrollmentReport, RegistrationReport, TransactionReport

urlpatterns = [
    path('<slug>/register-event', login_required(RegisterEvent.as_view()), name='register_event'),
    path('<slug>/student-list', login_required(RegisterStudentList.as_view()), name='register_student_list'),
    path('<registration_id>/detail', login_required(RegistrationDetail.as_view()), name='registration_detail'),
    path('<slug>/print-enroll-list', login_required(EnrollmentReport.as_view()), name='print_enroll_list'),
    path('<slug>/print-student-list', login_required(RegistrationReport.as_view()), name='print_student_list'),
    path('<slug>/print-transaction-list', login_required(TransactionReport.as_view()), name='print_transaction_list'),
]

event/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from .utils import get_unique_slug


# Create your models here.
class EventRecord(models.Model):
    slug = models.SlugField(unique=True)
    tipe_event = models.CharField(max_length=50)
    tema_event = models.CharField(max_length=75)

    penyelenggara = models.CharField(max_length=64)
    nama_event = models.CharField(max_length=110)
    event_pic = models.FileField(default='')
    event_banner = models.FileField(default='')
    biaya = models.FloatField()
    tanggal_awal_pendaftaran = models.DateField()
    tanggal_akhir_pendaftaran = models.DateField()
    tanggal_event = models.DateField()
    nomor_durasi = models.CharField(max_length=10)
    jenis_durasi = models.CharField(max_length=10)
    jurusan_eligible = models.CharField(max_length=100)
    angkatan_eligible = models.CharField(max_length=100)

    tautan_lanjutan_1 =  models.URLField(max_length=100)
    tautan_detail_1 = models.CharField(max_length=50)
    tautan_lanjutan_2 = models.URLField(max_length=100)
    tautan_detail_2 = models.CharField(max_length=50)
    tautan_lanjutan_3 = models.URLField(max_length=100)
    tautan_detail_3 = models.CharField(max_length=50)

    persyaratan_1 = models.CharField(max_length=50, default='')
    persyaratan_2 = models.CharField(max_length=50, default='')
    persyaratan_3 = models.CharField(max_length=50, default='')
    persyaratan_4 = models.CharField(max_length=50, default='')
    persyaratan_5 = models.CharField(max_length=50, default='')
    persyaratan_6 = models.CharField(max_length=50, default='')

    benefit_event_1 = models.CharField(max_length=100, default='')
    benefit_event_2 = models.CharField(max_length=100, default='')
    benefit_event_3 = models.CharField(max_length=100, default='')
    benefit_event_4 = models.CharField(max_length=100, default='')
    benefit_event_5 = models.CharField(max_length=100, default='')
    benefit_event_6 = models.CharField(max_length=100, default='')
    deskripsi = RichTextUploadingField()

    alumni = models.IntegerField(default=0)
    venue = models.CharField(max_length=50)
    narahubung = models.CharField(max_length=110)
    narahubung_pic = models.FileField(default='')
    narahubung_desc = RichTextUploadingField()

    registered_student = models.IntegerField(default=0)
    membutuhkan_pendaftaran = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, self.tema_event, self.tanggal_event)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.slug


class DataList(models.Model):
    place = models.CharField(max_length=50)
    number = models.IntegerField()

    def __str__(self):
        return self.place

event/views.py
from datetime import date

from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from registration.models import RegistrationRecord
from .forms import EventForm
from .models import EventRecord


# Create your views here.
class EventListView(TemplateView):
    template_name = 'event-list.html'

    def get(self, request, *args, **kwargs):
        try:
            tema = 'All'
            if kwargs.get('tema_event'):
                tema = kwargs['tema_event']
                event_list = EventRecord.objects.filter(tema_event=kwargs['tema_event']).order_by('-tanggal_event')
                print('aa')
            else:
                event_list = EventRecord.objects.all().order_by('-tanggal_event')
            return render(request, self.template_name, {'event_list': event_list, 'now': date.today(), 'tema':tema})

        except ObjectDoesNotExist:
            messages.error(request, 'Record Not Found')
            return redirect('home')


# noinspection PyBroadException
class EventDetail(TemplateView):
    template_name = 'event_detail.html'

    def get(self, request, *args, **kwargs):
        try:
            owner = False
            registered = True
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            if obj.user == request.user or request.user.is_superuser:
                owner = True
            else:
                try:
                    RegistrationRecord.objects.get(user=request.user, event=obj)
                except Exception:
                    registered = False
            return render(request, self.template_name,
                          {'obj': obj, 'owner': owner, 'registered': registered, 'now': date.today()})
        except ObjectDoesNotExist:
            messages.error(request, 'Event Tidak Ditemukan')
            return redirect('home')


# noinspection PyBroadException
class AddEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff:
                form = EventForm()
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except PermissionDenied:
            messages.error(request, 'Permission Denied')
            return redirect('home')

    def post(self, request):
        if True:
            if request.user.is_staff:
                form = EventForm(request.POST, request.FILES)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = request.user
                    form.save()
                    messages.success(request, 'Event Sukses Ditambahkan')
                    return redirect('event:event_detail', slug=temp.slug)
                else:
                    messages.error(request, 'Invalid Input')
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        # except Exception:
        #     messages.error(request, 'Permission Denied')
        #     return redirect('home')


# noinspection PyBroadException
class UpdateEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff or request.user.is_superuser:
                obj = EventRecord.objects.get(slug=kwargs['slug'])
                if obj.user == request.user or request.user.is_superuser:
                    form = EventForm(instance=obj)
                else:
                    raise PermissionDenied
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('home')

    def post(self, request, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            f = obj.biaya
            if obj.user == request.user or request.user.is_superuser:
                form = EventForm(request.POST, request.FILES, instance=obj)
                if form.is_valid():
                    fee = form.cleaned_data['biaya']
                    diff = fee - f
                    if diff != 0:
                        student_list = RegistrationRecord.objects.filter(event=obj)
                        for student in student_list:
                            student.balance += diff
                            student.save(update_fields=['balance'])
                    form.save()
                    messages.success(request, 'Event Sukses Diupdate')
                    return redirect('event:event_detail', kwargs['slug'])
                else:
                    messages.error(request, 'Invalid Input')
                return render(request, self.template_name, {'form': form})
            else:
                raise PermissionDenied
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('home')


class DeleteEvent(TemplateView):

    def get(self, request, *args, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            if str(obj.timestamp) == kwargs['timestamp'] and (obj.user == request.user or request.user.is_superuser):
                if obj.registered_student > 0:
                    raise PermissionDenied('Siswa telah terdaftar, Anda tidak bisa menghapus event ini.')
                obj.delete()
                messages.success(request, 'Event Sukses Dihapus')
            else:
                raise PermissionDenied('Permission Denied')
        except ObjectDoesNotExist:
            messages.error(request, 'Event tidak ditemukan')
            return redirect('home')
        except PermissionDenied as msg:
            messages.warning(request, msg)
            return redirect('account:consolidated_view_all')

event/templates/event-list.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Home | {{ block.super }}{% endblock %}
<main>{% block content %}</main>

<script defer src="https://unpkg.com/alpinejs@3.2.3/dist/cdn.min.js"></script>

<article x-data="slider" class="tw-relative tw-w-full tw-flex tw-flex-shrink-0 tw-overflow-hidden">
    <div class="tw-rounded-full tw-bg-gray-600 tw-text-white tw-absolute tw-top-5 tw-right-5 tw-text-sm tw-px-2 tw-text-center tw-z-10">
        <span x-text="currentIndex"></span>/
        <span x-text="images.length"></span>
    </div>

    <template x-for="(image, index) in images">
        <figure class="tw-h-96" x-show="currentIndex == index + 1" x-transition:enter="tw-transition tw-transform tw-duration-300"
        x-transition:enter-start="tw-opacity-0" x-transition:enter-end="tw-opacity-100"
        x-transition:leave="tw-transition tw-transform tw-duration-300" x-transition:leave-start="tw-opacity-100"
        x-transition:leave-end="tw-opacity-0">
        <img :src="image" alt="Image" class="tw-absolute tw-inset-0 tw-z-10 tw-h-full tw-w-full tw-object-cover tw-opacity-70" />
        <figcaption class="tw-absolute tw-inset-x-0 tw-bottom-1 tw-z-20 tw-w-96 tw-mx-auto tw-p-4 tw-font-light tw-text-sm tw-text-center tw-tracking-widest tw-leading-snug tw-bg-gray-300 tw-bg-opacity-25">
          AWS Educate adalah program pelatihan yang dirancang khusus untuk memperkenalkan konsep-konsep dasar dalam teknologi cloud computing dan memberikan keterampilan praktis bagi siswa SMK jurusan RPL dalam mengelola infrastruktur dan aplikasi cloud menggunakan layanan Amazon Web Services (AWS).
        </figcaption>
        </figure>
    </template>

    <button @click="back()"
        class="tw-absolute tw-left-14 tw-top-1/2 tw--translate-y-1/2 tw-w-11 tw-h-11 tw-flex tw-justify-center tw-items-center tw-rounded-full tw-shadow-md tw-z-10 tw-bg-gray-100 hover:tw-bg-gray-200">
        <svg class=" tw-w-8 tw-h-8 tw-font-bold tw-transition tw-duration-500 tw-ease-in-out tw-transform motion-reduce:tw-transform-none tw-text-gray-500 hover:tw-text-gray-600 hover:tw--translate-x-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M15 19l-7-7 7-7">
            </path>
        </svg>
    </button>

    <button @click="next()"
    class="tw-absolute tw-right-14 tw-top-1/2 tw-translate-y-1/2 tw-w-11 tw-h-11 tw-flex tw-justify-center tw-items-center tw-rounded-full tw-shadow-md tw-z-10 tw-bg-gray-100 hover:tw-bg-gray-200">
        <svg class=" tw-w-8 tw-h-8 tw-font-bold tw-transition tw-duration-500 tw-ease-in-out tw-transform motion-reduce:tw-transform-none tw-text-gray-500 hover:tw-text-gray-600 hover:tw-translate-x-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M9 5l7 7-7 7"></path>
        </svg>
    </button>
</article>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('slider', () => ({
            currentIndex: 1,
            images: [
                "{% static 'images/slide-example.jpg' %}",
                "{% static 'images/slide-example.jpg' %}",
                "{% static 'images/slide-example.jpg' %}",
                "{% static 'images/slide-example.jpg' %}",
                "{% static 'images/slide-example.jpg' %}",
            ],
            back() {
                if (this.currentIndex > 1) {
                    this.currentIndex = this.currentIndex - 1;
                }
            },
            next() {
                if (this.currentIndex < this.images.length) {
                    this.currentIndex = this.currentIndex + 1;
                } else if (this.currentIndex <= this.images.length){
                    this.currentIndex = this.images.length - this.currentIndex + 1
                }
            },
        }))
    })
</script>



<section class="tw-bg-white tw-py-8 tw-pb-12">

  <div class="container tw-mx-auto tw-flex tw-items-center tw-flex-wrap tw-pt-4">

      <nav id="store" class="tw-w-full tw-z-30 tw-top-0 tw-px-6 tw-py-1">
          <div class="tw-w-full container tw-mx-auto tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-mt-0 tw-px-2 tw-py-3">

              <a class="tw-uppercase tw-tracking-wide tw-no-underline hover:tw-no-underline tw-font-bold tw-text-gray-800 tw-text-xl " href="#">Eksplor Event Terdekat</a>

              <div class="tw-flex tw-items-center tw-hidden md:tw-block" id="store-nav-content">

                  <a class="tw-pl-3 tw-inline-block tw-no-underline hover:tw-text-black">
                      <svg class="tw-fill-current hover:tw-text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                          <path d="M7 11H17V13H7zM4 7H20V9H4zM10 15H14V17H10z" />
                      </svg>
                  </a>

                  <a class="tw-pl-3 tw-inline-block tw-no-underline hover:tw-text-black">
                      <svg class="tw-fill-current hover:tw-text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                          <path d="M10,18c1.846,0,3.543-0.635,4.897-1.688l4.396,4.396l1.414-1.414l-4.396-4.396C17.365,13.543,18,11.846,18,10 c0-4.411-3.589-8-8-8s-8,3.589-8,8S5.589,18,10,18z M10,4c3.309,0,6,2.691,6,6s-2.691,6-6,6s-6-2.691-6-6S6.691,4,10,4z" />
                      </svg>
                  </a>

                </div>
            </div>

            <div x-data="{show: false}" @click.away="show = false"> <button @click="show = ! show" class="tw-mt-4 tw-border-0 tw-block tw-bg-amber-200 tw-bg-amber-200 tw-text-black-700 tw-rounded-lg tw-px-6 tw-text-sm tw-py-3 tw-overflow-hidden focus:tw-outline-none focus:tw-border-white">
                    <div class="tw-flex tw-justify-between"> <span>Filter Berdasarkan Tema</span> <svg class="tw-fill-current tw-text-black-700 tw-text-xs" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                            <path d="M7 10l5 5 5-5z" />
                            <path d="M0 0h24v24H0z" fill="none" /></svg> </div>
                </button>
                <div x-show="show" class="tw-mt-2 tw-py-2 tw-bg-white tw-rounded-lg tw-shadow-xl"> 
                    <a href="{% url 'event:event_list' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="All Event">All</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Workshop' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Workshop">Workshop</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Kompetisi' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Kompetisi">Kompetisi</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Pelatihan' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Pelatihan">Pelatihan</a>
                    <a href="{% url 'event:event_tema_event' tema_event='PORAK' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Pekan Olahraga dan Kesenian Siswa">PORAK</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Kegiatan-Olahraga' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Kegiatan Olahraga">Kegiatan Olahraga</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Hang-Out' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Hang-Out / Main Bareng">Hang-Out</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Travelling' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Travelling">Travelling</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Kegiatan-Alam' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Kegiatan Alam">Kegiatan Alam</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Festival-Musik' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Festival Musik">Festival Musik</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Festival-Anime' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Festival Jepang">Festival Anime</a>
                    <a href="{% url 'event:event_tema_event' tema_event='Kegiatan-Rohis' %}" class="btn btn-sm btn-outline-secondary m-2" style="min-width: 50px;" title="Kegiatan Keagamaan Islam">Kegiatan Rohis</a>                </div>
                </div>
      </nav>


      {% if event_list|length > 0 %}
        <div class="tw-p-10 tw-grid tw-grid-cols-1 sm:tw-grid-cols-1 md:tw-grid-cols-5 lg:tw-grid-cols-5 xl:tw-grid-cols-4 tw-gap-2">
            {% for data in event_list %}    
                <a href="{% url 'event:event_detail' data.slug %}" class="hover:tw-no-underline hover:tw-text-black">
                <div class="tw-rounded tw-w-[90%] tw-h-[95%] tw-overflow-hidden">
                    {% if now <= data.tanggal_akhir_pendaftaran %}<img class="tw-object-cover tw-h-48 tw-w-96" src="{{ data.event_banner.url }}" alt="">
                    {% else %}<img class="tw-object-cover tw-h-48 tw-w-96 tw-contrast-50" src="{{ data.event_banner.url }}" alt="">{% endif %}
                    <div class="tw-py-2">
                    <div class="tw-font-bold tw-text-base tw-mb-2">{{ data.nama_event }}</div>
                    <div class="tw-flex tw-items-center tw-justify-start tw-w-[57%]">
                        <img class="tw-w-[18px]" src="{{ data.event_pic.url }}" alt="">
                        <span class="tw-text-xs tw-text-gray-500 tw-font-bold">&nbsp;&nbsp;{{ data.tanggal_event }}</span>
                    </div>
                    <p class="tw-text-gray-500 tw-text-sm pt-2 tw-font-bold">
                        Creator: {{ data.penyelenggara }}<br>{% if now <= data.tanggal_akhir_pendaftaran %}<span class="text-success">Pendaftaran dibuka</span>
                        {% else %}<span class="text-danger">Event telah berakhir</span>{% endif %}
                    </p>
                    </div>
                    <div class="tw-pb-2">
                    <span class="tw-inline-block tw-bg-gray-200 tw-rounded tw-px-2 tw-py-1 tw-text-xs tw-font-semibold tw-text-gray-700 tw-mr-2 tw-mb-2">{{ data.tema_event }}</span>
                    </div>
                </div>
                </a>
            {% endfor %}
        </div>
      {% else %}
      <div style="margin: 0 auto; margin-top: 20px;">
        <p class="tw-text-gray-500 tw-text-sm pt-2 tw-font-bold !tw-text-center">Event dengan kategori {{ tema }} tidak tersedia.</p>
      </div>
      {% endif %}
       
  </div>

</section>
{% endblock %}